// WhatsApp conversation session TTL (matches Meta's 24-hour window)
export const SESSION_TTL_SECONDS = 86400

// How long to keep a session in ANALYZING state before timing out
export const ANALYZE_TIMEOUT_MS = 60_000

// Max image file size accepted (in bytes) - 16MB
export const MAX_IMAGE_SIZE_BYTES = 16 * 1024 * 1024

// BullMQ queue names
export const QUEUES = {
  IMAGE_GENERATION: 'image-generation',
  FESTIVE_POST: 'festive-post',
  VIDEO_GENERATION: 'video-generation',
  CLEANUP: 'cleanup',
} as const

// Auto-delete Cloudinary images older than 48 hours
export const CLOUDINARY_IMAGE_MAX_AGE_MS = 48 * 60 * 60 * 1000

// Free tier lifetime credits
export const FREE_TIER_LIFETIME_CREDITS = 25

// Credits consumed per photo generation
export const CREDIT_COST_PHOTO = 5

// Credits consumed per festive post
export const CREDIT_COST_FESTIVE = 8

// Credits consumed per video generation
export const CREDIT_COST_VIDEO = 60

// Session state names (mirrors @jewel/shared-types SessionState)
export const STATES = {
  IDLE: 'IDLE',
  AWAITING_IMAGE: 'AWAITING_IMAGE',
  ANALYZING: 'ANALYZING',
  AWAITING_TEMPLATE: 'AWAITING_TEMPLATE',
  AWAITING_ASPECT_RATIO: 'AWAITING_ASPECT_RATIO',
  AWAITING_CONFIRMATION: 'AWAITING_CONFIRMATION',
  PROCESSING: 'PROCESSING',
  COMPLETE: 'COMPLETE',
  PRICE_CALC_WEIGHT: 'PRICE_CALC_WEIGHT',
  PRICE_CALC_MAKING: 'PRICE_CALC_MAKING',
  BILLING_METAL: 'BILLING_METAL',
  BILLING_WEIGHT: 'BILLING_WEIGHT',
  BILLING_MAKING: 'BILLING_MAKING',
  BILLING_STONE: 'BILLING_STONE',
  BILLING_DONE: 'BILLING_DONE',
  INVOICE_CUSTOMER_NAME: 'INVOICE_CUSTOMER_NAME',
  INVOICE_CUSTOMER_GSTIN: 'INVOICE_CUSTOMER_GSTIN',
  LEDGER_MENU: 'LEDGER_MENU',
  LEDGER_ADD_NAME: 'LEDGER_ADD_NAME',
  LEDGER_ADD_AMOUNT: 'LEDGER_ADD_AMOUNT',
  LEDGER_ADD_DESC: 'LEDGER_ADD_DESC',
  LEDGER_PAY_NAME: 'LEDGER_PAY_NAME',
  LEDGER_PAY_AMOUNT: 'LEDGER_PAY_AMOUNT',
  LEDGER_VIEW_NAME: 'LEDGER_VIEW_NAME',
  UPGRADE_SELECT: 'UPGRADE_SELECT',
  CREDIT_PACK_SELECT: 'CREDIT_PACK_SELECT',
  BIZ_NAME: 'BIZ_NAME',
  BIZ_GSTIN: 'BIZ_GSTIN',
  BIZ_ADDRESS: 'BIZ_ADDRESS',
  BIZ_STATE: 'BIZ_STATE',
  BIZ_PHONE: 'BIZ_PHONE',
  BATCH_COLLECTING: 'BATCH_COLLECTING',
  BATCH_TEMPLATE: 'BATCH_TEMPLATE',
  BATCH_ASPECT_RATIO: 'BATCH_ASPECT_RATIO',
  BATCH_CONFIRM: 'BATCH_CONFIRM',
  BATCH_PROCESSING: 'BATCH_PROCESSING',
  FESTIVE_BRAND_LOGO: 'FESTIVE_BRAND_LOGO',
  FESTIVE_BRAND_NAME: 'FESTIVE_BRAND_NAME',
  FESTIVE_BRAND_PHONE: 'FESTIVE_BRAND_PHONE',
  FESTIVE_FESTIVAL_INPUT: 'FESTIVE_FESTIVAL_INPUT',
  FESTIVE_CONFIRM: 'FESTIVE_CONFIRM',
  FESTIVE_PROCESSING: 'FESTIVE_PROCESSING',
  AWAITING_JEWEL_TYPE: 'AWAITING_JEWEL_TYPE',
  BATCH_JEWEL_TYPE: 'BATCH_JEWEL_TYPE',
  VIDEO_UPLOAD: 'VIDEO_UPLOAD',
  VIDEO_TEMPLATE: 'VIDEO_TEMPLATE',
  VIDEO_SUB_TEMPLATE: 'VIDEO_SUB_TEMPLATE',
  VIDEO_ASPECT_RATIO: 'VIDEO_ASPECT_RATIO',
  VIDEO_CONFIRM: 'VIDEO_CONFIRM',
  VIDEO_PROCESSING: 'VIDEO_PROCESSING',
} as const

// Meta Cloud API base URL
export const META_API_BASE = 'https://graph.facebook.com/v21.0'

// Supported languages for auto-detection
export const SUPPORTED_LANGUAGES = ['en', 'hi', 'gu', 'ta', 'te', 'mr'] as const
