// ─── Video Template Types ────────────────────────────────────────────────────

export interface VideoSubTemplate {
  id: string
  name: string
  previewUrl: string
  frame0Prompt: string
  frame1Prompt: string
  videoPrompt: string
  frame0UsesLogo: boolean  // whether Frame 0 uses brand logo as input
}

export interface VideoTemplate {
  id: string
  name: string
  category: string
  previewUrl: string
  subTemplates: VideoSubTemplate[]
}

// ─── Template Definitions ────────────────────────────────────────────────────

export const VIDEO_TEMPLATES: VideoTemplate[] = [
  {
    id: 'vtpl_box_reveal',
    name: 'Box Reveal',
    category: 'Reveal',
    previewUrl: 'https://res.cloudinary.com/dhbq4ad3t/image/upload/v1776250157/box_celestial_prev_oyuwpq.png',
    subTemplates: [
      {
        id: 'vsub_celestial',
        name: 'Celestial Reveal',
        previewUrl: 'https://res.cloudinary.com/dhbq4ad3t/image/upload/v1776250157/box_celestial_prev_oyuwpq.png',
        frame0UsesLogo: true,
        frame0Prompt: 'Use the attached brand logo as the reference for the lid branding. Create a premium luxury jewelry campaign image in a fixed celestial teaser state. Show a fully closed luxury jewelry box centered in frame, placed in a refined cosmic setting. The scene must use this fixed celestial template language: a centered composition, a soft circular halo behind the box, a deep midnight-blue and navy celestial background, subtle indigo and teal nebula haze, an elegant star field, a faint sparkling dust ring around the base, and a dark glossy reflective surface below. This is the pre-reveal dormant frame, so the scene should feel calmer, darker, quieter, and more mysterious. The halo should be softer, dimmer, and slightly tighter. The nebula should feel more distant and restrained. The stars should be subtler and less radiant. The sparkle ring around the base should be faint and controlled. The floor reflection should be darker and weaker. There must be no inner glow from the box, no reveal burst, and no activated magical energy. The jewelry box must be perfectly closed and flush, with zero visible gap, zero visible interior, zero visible lining, zero visible cushion, and zero jewelry visible. The logo on the lid should be rendered as a premium engraved, debossed, or blind-embossed mark naturally integrated into the material. Use the logo as shape reference only. It must look built into the lid, elegant and tactile, not pasted, printed, sticker-like, glossy, or floating. Keep everything stable, centered, cinematic, premium, and uncluttered. This frame should feel like a luxury teaser before activation. No text. No watermark.',
        frame1Prompt: 'Use the attached jewelry item as the exact product reference. Create a premium luxury jewelry campaign image in the same celestial template, but now in an awakened reveal state. Show the same jewelry box opened elegantly, with the jewelry beautifully presented inside as the hero. The jewelry must remain faithful to the reference in silhouette, structure, proportions, stone placement, and overall design identity. Do not redesign, distort, simplify, or replace the jewelry. Keep the same celestial world and same centered composition language as the teaser frame: centered box, circular halo behind it, deep midnight-blue celestial sky, nebula atmosphere, elegant stars, sparkling ring around the base, and a glossy reflective surface below. However, this must now feel like the activated version of that same world. Make the scene visibly more radiant and alive. The halo should be larger, brighter, fuller, and more luminous. The nebula should be richer, more visible, and slightly expanded outward. The stars should be brighter and more sparkling. The dust ring around the base should be more energized and complete. The floor reflection should be stronger and cleaner. Add a soft inner reveal glow from inside the box so the jewelry becomes the focal point. To support animation, the celestial background elements should feel like they have subtly shifted and awakened compared to the closed frame: nebula clouds may drift slightly, particles may spread outward, the halo may expand, stars may twinkle more clearly, and the sparkle ring may appear more active and opened up. These changes should be elegant and controlled, not chaotic. The open frame should clearly feel like the same world after activation. Keep the composition premium, stable, centered, cinematic, and uncluttered. No text. No watermark.',
        videoPrompt: 'Create a smooth luxury jewelry reveal animation in a fixed celestial campaign template. Begin with a fully closed premium jewelry box in a calm, dormant celestial world, then transition into the same box opening gracefully to reveal the jewelry inside. The composition must remain centered, elegant, and stable throughout. Keep the visual language consistent across the animation: a centered jewelry box, a soft circular halo behind it, a deep midnight-blue celestial sky, subtle nebula atmosphere, elegant stars, a sparkling dust ring around the base, and a dark glossy reflective surface below. The animation should clearly show a dormant-to-awakened transformation: at the start, the scene feels quieter, dimmer, and more mysterious; as the box opens, the celestial world gradually becomes brighter, richer, and more alive; the halo softly expands and brightens; stars shimmer more; cosmic particles become slightly more active; the sparkle ring around the base becomes more energized; the floor reflection becomes a little stronger; and a soft inner glow emerges from the box as the jewelry is revealed. The motion must feel premium, cinematic, slow, and graceful. The lid should open smoothly and naturally, with no sudden movement. The camera may have a very slight push-in or subtle floating parallax, but the frame must remain stable and centered. Background motion should stay soft and elegant: gentle nebula drift, faint particle movement, subtle star twinkle, and delicate light breathing. The result should feel like a luxury celestial teaser transforming into a magical jewelry reveal, while preserving the same template structure from beginning to end. Avoid fast movement, jitter, scene redesign, box shape changes, jewelry distortion, sudden zooms, chaotic particles, excessive magical effects, random new objects, heavy sci-fi effects, text',
      },
      {
        id: 'vsub_floral_sky',
        name: 'Floral Sky',
        previewUrl: 'https://res.cloudinary.com/dhbq4ad3t/image/upload/v1776433197/Gemini_Generated_Image_fl8gasfl8gasfl8g_expa0w.png',
        frame0UsesLogo: true,
        frame0Prompt: 'Use the attached brand logo as the lid branding reference. Create a premium luxury jewelry campaign image in a dreamy floral sky teaser state. Show a fully closed luxury jewelry box floating gracefully in air, centered in frame, wrapped with an elegant ribbon. The scene should feel soft, poetic, refined, and luxurious. The world should use this fixed visual language: a beautiful open sky backdrop, warm soft daylight, drifting flower petals, airy depth, a premium floating jewelry box, and a ribbon elegantly wrapped around or flowing around the box. The mood should feel romantic, graceful, serene, and cinematic. This is the pre-reveal dormant frame, so the scene should feel calmer and more restrained. Petals should drift softly and sparsely. The sky should feel serene and clean, with gentle light and subtle atmosphere. The ribbon should feel composed and elegant, not explosive or chaotic. The overall mood should feel quiet and suspended, like a luxury teaser before activation. The jewelry box must be perfectly closed and flush, with zero visible interior and zero jewelry visible. The attached brand logo must appear on the lid as a premium, naturally integrated branding detail. Use the logo as a shape reference and adapt it beautifully into the box material. It should feel like an elegant luxury jewelry-box mark — engraved, debossed, embossed, foil-pressed, stitched, embroidered, or otherwise naturally crafted into the lid depending on the material of the box. It must not look pasted, sticker-like, printed flat, or artificially overlaid. The logo should be clearly visible, centered on the lid, tasteful, refined, and premium, while still feeling like a natural part of the box. Keep the composition centered, airy, premium, and uncluttered. No text. No watermark.',
        frame1Prompt: 'Use the attached Frame 1 image as the exact master reference for the jewelry box. Also use the attached jewelry item as the exact reference for the ring inside. Create the same exact box from Frame 1, in the same floating sky scene, but now in an opened reveal state. This is not a redesign of the box. It is the same identical box, only opened. Preserve the exact box shape, box proportions, lid shape, lid thickness, base thickness, corner softness, outer silhouette, outer velvet material, outer burgundy and plum color, visible seams and construction, camera angle, floating position, scale in frame, and overall composition. Do not change the box design in any way. Do not make it taller, squarer, rounder, thinner, wider, cleaner, simpler, or more generic. Do not replace the box with a different jewelry box. The opened version must look like Frame 1 itself has opened. The box should now be open gracefully, with the attached jewelry visible inside as the hero. The jewelry must remain faithful to the reference in silhouette, proportions, stone placement, and design identity. Do not redesign or distort the jewelry. No branding logo should be visible once the box is open. No ribbon should be visible in Frame 2. The opened box must still feel like the same luxury box from Frame 1, only after opening. The interior should feel like the natural inside of that same box, not a newly designed insert from another box style. The sky world must remain the same dreamy floral environment as Frame 1. However, for animation continuity, the flowers and petals must feel like the next flowing moment of the same scene: use the same flower and petal language as Frame 1, include more petals and blossoms than Frame 1, place them in clearly different positions, do not repeat the same petal arrangement from Frame 1, make them feel like they are continuously drifting and falling through the air, and allow some petals to be closer, farther, higher, lower, entering frame, or leaving frame. The open frame should feel brighter, softer, and more awakened than Frame 1, with a subtle reveal glow around the jewelry. Keep everything premium, airy, graceful, and animation-friendly. No text. No watermark.',
        videoPrompt: 'Create a premium cinematic jewelry reveal animation in a dreamy floral sky setting. Start with a closed burgundy velvet jewelry box floating gently in the air, wrapped with an elegant satin ribbon and surrounded by softly drifting flower petals and small blossoms against a warm cloudy sky. The jewelry is already physically inside the box from the very first frame, fixed in its final resting position on the inner cushion, but hidden from view because the box is closed. As the animation begins, the ribbon loosens and unwraps gracefully from the box, flowing outward naturally in soft elegant curves. After the ribbon clears, the same box opens slowly and smoothly on its hinge, revealing the jewelry already inside. The jewelry must never pop in, fade in, scale in, teleport, or appear late. It should only become visible because the lid opens. Throughout the shot, petals and blossoms should continuously drift and fall downward through the scene with soft natural airflow, creating a beautiful sense of motion and depth. Some petals should pass closer to camera, some farther away, and their positions should keep changing naturally through the animation. The sky remains dreamy and airy, becoming slightly brighter and more magical as the reveal progresses. Use a soft cinematic push-in or very subtle floating parallax, but keep the composition elegant and stable. Motion should feel slow, luxurious, graceful, and high-end. Add a gentle warm reveal glow inside the box once the jewelry becomes visible, but use it only as illumination, not as a magical creation effect. End on a refined hero shot of the open box floating in the sky with the jewelry beautifully revealed inside and petals still falling around it. The jewelry must already be inside the closed box from the first frame and remain fixed in place throughout the animation, becoming visible only as the ribbon unwraps and the lid opens.',
      },
    ],
  },
]

// ─── Lookup Helpers ──────────────────────────────────────────────────────────

export function getVideoTemplate(templateId: string): VideoTemplate | undefined {
  return VIDEO_TEMPLATES.find((t) => t.id === templateId)
}

export function getVideoSubTemplate(
  templateId: string,
  subTemplateId: string,
): VideoSubTemplate | undefined {
  const template = getVideoTemplate(templateId)
  return template?.subTemplates.find((s) => s.id === subTemplateId)
}
